#!/usr/bin/env python

from __future__ import print_function
import argparse
import re
import sys


parser = argparse.ArgumentParser()
parser.add_argument('--perc', type=float, default=0.25,
                    help='maximum repeat content as a fraction of the total '
                    'iLocus length; default is 0.25')
parser.add_argument('--bp', type=int, default=500, 
                    help='maximum repeat content in bp; default is 500')
parser.add_argument('infile', type=argparse.FileType('r'), help='input file '
                    '(generated by `bedtools coverage`)')
args = parser.parse_args()

for line in args.infile:
    fields = line.rstrip().split('\t')
    assert len(fields) == 13, line
    bp = int(fields[10])
    perc = float(fields[12])
    label = re.search('Name=([^;\n]+)', line).group(1)
    if bp < args.bp and perc < args.perc:
        print(label)
    else:
        print(label, file=sys.stderr)
    
